### ISSUE TITLE
style

### ISSUE THREAD

**Issue by dericed** [pdicamillo/datxtract#1]
Do you recommend a particular coding style? The documents in source contain a variety of spacing, indentation and trailing space. Could we consider running these through `clang-format`?

**Comment by pdicamillo** [comment]
I've updated the source to remove tabs and trailing space. I don't think tabs are a good idea for an open source project, and the trailing space was unintentional. I indent code blocks every 4 columns, and would continue that even though tab characters are not being used. I try to keep lines to no longer than 80 characters, although I will occasionally make an exception for clarity if the lines are not too much longer. If parameters to a function don't all fit on one line, I indent the subsequent lines to line up with the first parameter. I use /* */ for block comments outside of code,  and to comment out blocks of code. So that will work I use // for comments within code. In general, I try to follow a consistent style, but I don't rule out making isolated exceptions for clarity.

I've never used clang-format, but I looked into it after your comment. I'd be willing to consider using it if it can be configured with a style that comes close to my style. I was looking for examples of what the pre-defined styles look like, but didn't find any. If you'd like to suggest one or more styles for me to try, I'll see what I think.
